apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: prod-gitops-guide-vvm
  owner: prod-gitops-guide-vvm
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/prod-gitops-guide-vvm/multi-tenancy-gitops-apps.git
